spring:
  application:
    name: cloud-order
  cloud:
    # 服务注册与发现 配置
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos

# 服务端口及访问路径配置
server:
  port: 9001
  servlet:
    context-path: /cloud-order

# actuator配置
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
